name: LaTeX Build and Release

on:
  push:
    branches:
      - main

env:
  PDF_FILENAME: Project_Report.pdf
  RELEASE_NAME: Release ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install LaTeX
        run: |
          sudo apt-get update && \
          sudo apt-get install -y texlive-full

      - name: Build LaTeX
        run: |
          cd src
          pdflatex main.tex
          bibtex main
          pdflatex main.tex
          pdflatex main.tex

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            Changes in this release:
            - added new feature
            - fixed bugs
          draft: false
          prerelease: false

      - name: Upload PDF as Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/${{ env.PDF_FILENAME }}
          asset_name: ${{ env.PDF_FILENAME }}
          asset_content_type: application/pdf
